#!/data/data/com.termux/files/usr/bin/bash
# Start Termux X11
termux-x11 :1 -legacy-drawing &
sleep 4
# Export DISPLAY variable
export DISPLAY=:1

# Start Openbox session
openbox-session &

# Start xfce4-panel
xfce4-panel &

# Start xcompmgr with minimal fading
xcompmgr -c -t3 -l5 -f &

# Start PCManFM with desktop mode
pcmanfm --desktop &

# Set a wallpaper using Nitrogen
nitrogen --set-auto ~/.icons/cool.png &

# Start Cairo-Dock
cairo-dock -f &

# Start Termux X11 app
sleep 4
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity
